name: Deploy to EC2 Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create WAR structure
        run: |
          mkdir -p build/WEB-INF/classes
          mkdir -p build/WEB-INF/lib

          # Compiler les classes Java
          javac -d build/WEB-INF/classes -classpath "/usr/share/tomcat/lib/servlet-api.jar" src/mypackage/*.java

          # Copier les fichiers JSP et web.xml
          cp index.jsp build/
          cp tasks.jsp build/
          cp WEB-INF/web.xml build/WEB-INF/

          # Créer le fichier .war
          cd build
          jar -cvf damien.war *

      - name: Deploy WAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: build/damien.war
          target: /opt/tomcat/webapps/
